spring:
  application:
    name: 'eureka server'
server:
  port: 9090
eureka:
  client:
    registryWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9090/eureka